sonar.projectKey=Andrey15211_Auto-configVPN
sonar.organization=andrey15211

# Ignore rules that do not apply to open-source companion apps
sonar.issue.ignore.multicriteria=e1,e2
# Obfuscation requirement for open-source utility client
sonar.issue.ignore.multicriteria.e1.ruleKey=kotlin:S7204
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
# Gradle lockfile requirement
sonar.issue.ignore.multicriteria.e2.ruleKey=text:S8569
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
